version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/ton_client"
    schedule:
      interval: "weekly"

  - package-ecosystem: "cargo"
    directory: "/ton_sdk"
    schedule:
      interval: "weekly"
