pub const DEFAULT_NETWORK_RETRIES_LIMIT: isize = -1;
pub const DEFAULT_NETWORK_RETRIES_TIMEOUT: isize = 1000;
pub const DEFAULT_EXPIRATION_RETRIES_LIMIT: isize = 20;
pub const DEFAULT_EXPIRATION_RETRIES_TIMEOUT: isize = 1000;
