[package]
authors = [ 'Alexey Vavilin <mnogoborec@mail.ru>' ]
edition = '2018'
name = 'test_sdk_v1'
version = '0.1.0'

[dependencies]
serde_json = '1.0.41'
tokio = { features = [ 'rt-threaded', 'macros', 'sync' ], version = '0.2.13' }
ton_client = { path = '../../ton_client' }
